### ISSUE TITLE
How do you print this item and get it to work?

### ISSUE THREAD

**Issue by flybd5** [nasa/NASA-3D-Resources#30]
Without clear parameters on how to print the ratchet wrench uplink.stl I find it impossible to get it to work correctly. Even at the finest resolution of my Flashforge Dreamer the ratchet mechanism will not budge. Has anybody gotten this to work correctly? Ever?

**Comment by Marsfan** [comment]
@flybd5 Which model in particular is giving you trouble? 

Disclaimer: I am not affiliated with NASA in any way, just someone hoping to help

**Comment by flybd5** [comment]
The wrench. That it is a ratchet wrench is a myth and I don't see how any astronaut could have used this tool as such.

**Comment by Marsfan** [comment]
I looked around at the wrench models, there are at least two that are ratchets, one is called uplink.stl and the other is called ratchet.fbx. As far as I can tell, non of them are designed to actually function as a wrench. They are more intended for use either as a decoration, or use within other 3D projects (like in a game).

**Comment by flybd5** [comment]
Your information is incorrect. The one that I am referring to is documented as the actual design that was sent to the ISS.

**Comment by Marsfan** [comment]
My apologies. I looked at the model again. I had things enabled incorrectly in my viewer. Looking at it now, I do indeed see that it looks like it should work as a ratchet.
My suspicion is that the 3D printer is accidentally fusing the parts together somehow, whether it be due to the filament expanding, or the support structure getting in the way. 


I did find some videos on youtube of people printing it (just search on YouTube NASA 3d printer wrench and there are many videos)
https://www.youtube.com/watch?v=z5Iqr90Z_9Q
https://www.youtube.com/watch?v=mVOjwYw9jt8

I do not have access to a 3D printer myself, so I cannot test it, but I would double check your supports settings.

**Comment by flybd5** [comment]
I think you are missing my point. The NASA 3D resource web site should not simply throw the STL files out there with zero guidance, and people should not have to go dumpster diving on YouTube (that aussie video is damn near unintelligible) to figure out how to get the models to print correctly. The consequence of that is that people who want to try their hand at printing this will easily be discourage, and it works against getting kids interested in all this.

**Comment by ldo** [comment]
My suspicion is, there is little more support for this repo than simply putting the models out there. They probably don’t have time (or budget) to do more than that. Look at the number of unaddressed issues right here for example.

**Comment by flybd5** [comment]
Probably. But if they are not going to do it right, then they should just not do it at all...

**Comment by ldo** [comment]
Some of us would rather have the models.

**Comment by arc-webservices** [comment]
I've also seen that the models on the NASA3D website lack documentation. It's a problem without a solution because no quality control has been imposed on any contributor. The idea was that it's better to share at least the model even if it lacks documentation or properly linked textures.
